name: Deploy to gh-pages

on:
  push:
    branches:
      - main

jobs:
  gh-pages-deploy:
    name: Deploying to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Clean install dependencies
        run: yarn install

      - name: Build app
        run: yarn run build

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          cname: mbfassnacht.de
